class Student:
    def __init__(self, name):
        self.name = name

    def show(self):
        print("Student:", self.name)

class Teacher:
    def __init__(self, name):
        self.name = name

    def show(self):
        print("Teacher:", self.name)

class Admin:
    def __init__(self, name):
        self.name = name

    def show(self):
        print("Admin:", self.name)